apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: devconf
spec:
  type: git
  params:
  - name: url
    value: https://github.com/khrm/devconf-tektonbooth-build-release
---

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: test
spec:
  inputs:
    resources:
    - name: workspace
      type: git
      targetPath: src
  steps:
  - name: test
    image: golang
    workingdir: /workspace/src
    command: ["go"]
    args: ['test', '-v', '-vet=off']

---

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build
spec:
  inputs:
    resources:
    - name: workspace
      type: git
      targetPath: src
  outputs:
    resources:
    - name: workspace
      type: git
  steps:
  - name: build-server
    image: golang:alpine
    workingdir: /workspace/src
    command: ["go"]
    args: ['build', '-o', '/workspace/src/hello']

---

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: publish-release
spec:
  inputs:
    resources:
    - name: workspace
      type: git
      targetPath: src
  steps:
    - name: publish-release
      image: centos
      workingdir: /workspace/src
      command: ["./publish.sh"]
      env:
        - name: ASSETS_PATH
          value: hello
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github
              key: access-token

---

apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-release
spec:
  resources:
  - name: source-repo
    type: git
  tasks:
  - name: test
    taskRef:
      name: test
    resources:
      inputs:
      - name: workspace
        resource: source-repo
  - name: build
    runAfter: [test]
    taskRef:
      name: build
    resources:
      inputs:
      - name: workspace
        resource: source-repo
      outputs:
      - name: workspace
        resource: source-repo
  - name: publish-release
    runAfter: [build]
    taskRef:
      name: publish-release
    resources:
      inputs:
      - name: workspace
        resource: source-repo
        from: [build]
